version: '3.8'
services:
  database:
    image: mariadb
    volumes:
      - './data/mariadb/:/var/lib/mysql/'
    environment:
      MYSQL_DATABASE: iprwc
      MYSQL_ROOT_PASSWORD: r2yxfbs633KEAoQa3fbYH8VGXQJK74EHxtNsA7Gm
    restart: always
    ports:
      - 3306:3306
    networks:
      - internal
  frontend:
    build: ./frontend/
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - internal
      - web
  backend:
    build: ./backend/
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database
    links:
      - database:iprwc
    networks:
      - internal
      - web
networks:
  web:
    external: true
  internal:
    external: false
