version: '3.8'
services:
  database:
    image: mariadb
    environment:
      MYSQL_DATABASE: iprwc
      MYSQL_ROOT_PASSWORD: admin
    restart: always
    ports:
      - 3306:3306
  frontend:
    build: ./frontend/
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./backend/
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database
    links:
      - database:iprwc
